### ISSUE TITLE
Rosetta installation error

### ISSUE THREAD

**Issue by jjz2023** [RosettaCommons/rosetta#190]
I downloaded  rosetta_bin_ubuntu_3.14_bundle.tar.bz2, executed the commend lines and got errors.
>tar -xf rosetta_bin_ubuntu_3.14_bundle.tar.bz2
>cd rosetta3.14/main/source
>python3.12 -m pip install scons
>./scons.py -j 20 mode=release bin

How to fix the install errors as followings:
/home/bin/rosetta3.14/main/source/./scons.py:105: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
SCons import failed. Unable to find engine files in:
  /home/bin/rosetta3.14/main/source/external/scons-local/scons-local-3.0.4
  /home/bin/miniconda3/lib/python3.12/site-packages/scons-3.0.4
  /home/bin/miniconda3/lib/scons-3.0.4
  /home/bin/miniconda3/lib/python3.1/site-packages/scons-3.0.4
  /home/bin/miniconda3/lib/scons-3.0.4
  /home/bin/miniconda3/lib/python3.12/site-packages/scons
  /home/bin/miniconda3/lib/scons
  /home/bin/miniconda3/lib/python3.1/site-packages/scons
  /home/bin/miniconda3/lib/scons
Traceback (most recent call last):
  File "/home/bin/rosetta3.14/main/source/./scons.py", line 196, in <module>
    import SCons.Script
  File "/home/bin/rosetta3.14/main/source/external/scons-local/scons-local-3.0.4/SCons/__init__.py", line 43, in <module>
    import SCons.compat
  File "/home/bin/rosetta3.14/main/source/external/scons-local/scons-local-3.0.4/SCons/compat/__init__.py", line 64, in <module>
    import imp  # Use the "imp" module to protect imports from fixers.
    ^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'

**Comment by roccomoretti** [comment]
First off, the "bin" download should already have a version of Rosetta pre-complied for you (though it would be a ".static.linuxgccrelease" executable name instead of a ".default.linuxgccrelease" or a plain ".linuxgccrelease" -- it should function the same, though.) -- if that version works, you don't need to do the compilation. 

You also shouldn't need to install the scons python package -- Rosetta ships with a complete version of Scons.

The issue you're running into when compiling is that the version of SCons which ships with Rosetta 3.14 is not compatible with newer versions of Python. This has since been fixed in the Github/development version of Rosetta. If you still want to compile Rosetta 3.14, you'll need to use a Python version of 3.11 or before. Alternatively, you may be able to use an externally installed recent version of SCons versus the `rosetta3.14/main/source/./scons.py` script.

**Comment by ZY3082178168** [comment]
python3 ./scons.py -j40 mode=release bin后出现以下错误，是因为什么呀Traceback (most recent call last):
  File "./scons.py", line 1, in <module>
    external/scons-local/scons.py
NameError: name 'external' is not defined

**Comment by roccomoretti** [comment]
@ZY3082178168 First off, it's best to open up a new discussion if the symptoms you're seeing are different from the original poster.

But I'm guessing you're on Windows, and have used cloned Rosetta using git. Git on Windows does not always work well with symlinks, and you're seeing the results of that. (You don't have a symlink, but rather a plain text file with the path to the place where the symlink points.)

Rosetta isn't really built to compile on Windows -- you'll want to use a Unix-like operating system like Linux or MacOS. If you are using a Windows machine, I'd recommend installing the Windows Subsystem for Linux, which allows you to run a Linux environment under Windows. Then install and run Rosetta from within the WSL environment.

**Comment by roccomoretti** [comment]
It looks like this issue has been addressed. If that assessment is incorrect, feel free to re-open it with any remaining questions you have, or to open a new discussion at https://github.com/RosettaCommons/rosetta/discussions
